server:
  port: 8001


spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/master?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 106

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
#      defaultZone: http://localhost:7001/eureka

mybatis:
  type-aliases-package: com.springcloud.test.entity
  mapper-locations: classpath*:mapper/*.xml
logging:
  level:
    com.springcloud.test: trace
